bin/bvpn

diff --git a/bin/bvpn b/bin/bvpn
--- a/bin/bvpn
+++ b/bin/bvpn
@@ -1,21 +1,22 @@
 #!/bin/bash
 
-sudo echo 'Root access worked. Proceeding ...' || { echo 'Could not get root access'; exit; }
+# sudo echo 'Root access worked. Proceeding ...' || { echo 'Could not get root access'; exit; }
 
 noprox
 sleep 1
 pkill -9 ssh
+sleep 2
 
 
-sudo networksetup -removepreferredwirelessnetwork en0 "Comfort Inn WIFI Guest"
-networksetup -setairportpower en0 off
-echo 'wait for 5 seconds ...'
-sleep 5
-networksetup -setairportpower en0 on
-echo 'wait for 5 seconds again ...'
-sleep 5
-networksetup -setairportnetwork en0 "Comfort Inn WIFI Guest"
-read -p 'press something: ' x
+#sudo networksetup -removepreferredwirelessnetwork en0 "Comfort Inn WIFI Guest"
+#networksetup -setairportpower en0 off
+#echo 'wait for 5 seconds ...'
+#sleep 5
+#networksetup -setairportpower en0 on
+#echo 'wait for 5 seconds again ...'
+#sleep 5
+#networksetup -setairportnetwork en0 "Comfort Inn WIFI Guest"
+#read -p 'press something: ' x
 tmux new-session -s ssh -d bash -c 'ssh -D 9999 tron'
 sleep 1
 prox -d 9999
