tidec genc

diff --git a/bin/genc b/bin/genc
--- a/bin/genc
+++ b/bin/genc
@@ -1,24 +1,51 @@
 #!/bin/bash
-infile="$1"
-
 umask 077
 
-main() {
-  op=enc
-  if [[ "$1" == '-e' ]]; then
-    op=enc
-    infile="$2"
-  elif [[ "$1" == '-d' ]]; then
-    op=dec
-    infile="$2"
-  fi
+tmpdir=''
+# Process options using getopt
+while getopts ":t:ed" opt; do
+    case "$opt" in
+        t)
+            tmpdir="$OPTARG"
+            ;;
+        e)
+            op=en
+            ;;
+        d)
+            op=dec
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG"
+            usage
+            ;;
+        :)
+            echo "Option -$OPTARG requires an argument."
+            ;;
+    esac
+done
 
+# Shift the processed options out of the argument list
+shift $((OPTIND - 1))
+
+if [[ "$tmpdir" == '' ]]; then
+    tmpdir=$(mktemp -d -t genc-XXXX)
+fi
+mkdir -p "$tmpdir"
+if [[ ! -d "$tmpdir" ]]; then
+    echo "No tmpdir \"$tmpdir\""
+    exit 1
+fi
+
+export op
+export tmpdir
+
+main() {
+  local infile="$1"
   if [[ "$infile" == '' ]]; then
     echo "Need infile"
     exit 1
   fi
 
-  local tmpdir=$(mktemp -d -t genc-XXXX)
   if [[ "$op" == 'enc' ]]; then
     if [[ -f "$infile" ]]; then
       outfile="${tmpdir}/"$(basename "$infile").gpg
@@ -73,7 +100,6 @@ do_enc_gpg() {
   local cryptfile="$2"
   rm -f crypt.gpg
   local status
-  local tmpd=$(mktemp -d -t genc-XXXX)
   if [[ -d "$plainfile" ]]; then
     local ind=$(cd "$(dirname "$plainfile")" && pwd -P)
     local bn=$(basename "$plainfile")
@@ -102,7 +128,6 @@ do_dec_gpg() {
   local plainfile="$2"
   local status=0
   if [[ "$cryptfile" =~ \.b64$ ]]; then
-    local tmpdir=$(mktemp -d -t genc-XXXX)
     base64 -d <"$cryptfile" >"$tmpdir/a.gpg"
     gpg --passphrase-fd 0 --batch -d -o "$plainfile" "$tmpdir/a.gpg" 2>/dev/null <<<"$mypass"
     status=$?
