lmount

diff --git a/bin/lmount b/bin/lmount
--- a/bin/lmount
+++ b/bin/lmount
@@ -13,14 +13,27 @@ veracrypt='/Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt'
 mountpoint=/b/om/l
 vera_volume=''
 
-if [[ $vera_volume == '' ]]; then
-  for v in '/Volumes/3TB/om/LCRUZER.vol' '/Volumes/1TB/CRUZER-20GB-MacOS.vol'; do
-    if [[ -f $v ]]; then
-      vera_volume=$v
-      break
-    fi
-  done
+tmpdir=$(mktemp -d)
+ls -1tr \
+/Volumes/3TB/om/LCRUZER.vol \
+/Volumes/1TB/CRUZER-20GB-MacOS.vol \
+/Volumes/data/LCRUZER.vol \
+>$tmpdir/volfiles.txt 2>/dev/null
+
+n=$(wc -l $tmpdir/volfiles.txt | awk '{print $1}')
+if [[ $n == 0 ]]; then
+  :
+elif [[ $n == 1 ]]; then
+  vera_volume=$(cat $tmpdir/volfiles.txt)
+else
+  echo
+  echo 'You have multiple vera volumes. Not knowing which one to do, aborting.'
+  echo
+  cat $tmpdir/volfiles.txt
+  rm -rf $tmpdir
+  exit 1
 fi
+
 if [[ $vera_volume == '' ]]; then
   # % mount
   # /dev/disk1 on / (hfs, local, journaled)
