vmount

diff --git a/bin/vmount b/bin/vmount
--- a/bin/vmount
+++ b/bin/vmount
@@ -2,8 +2,12 @@
 
 export PATH=$HOME/bin:$HOME/gcode/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
 
-mkdir -p ~/b/om/p
 mountpoint=~/b/om/p/CRUZER
+mkdir -p "$mountpoint"
+if [[ ! -d "$mountpoint" ]]; then
+    echo "ERROR: Failed to create Mountpoint \"$mountpoint\""
+    exit 1
+fi
 volpath=''
 algo=''  # 'vera' or 'luks' or 'dmg'
 veracrypt=''
